# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build, test, tag and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ all ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fregante/setup-git-user@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies with pip
      run: |
        python -m pip install --upgrade pip
        pip install wheel pytest bump2version==1.0.0
        pip install .
    - name: Test with pytest
      run: |
        pytest
    - name: Increment version number and tag
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        bump2version patch
        git push --follow-tags
    - name: Deploy to PyPi
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        pip install setuptools
        pip install twine
        python setup.py sdist bdist_wheel
        twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
      
