name: Build, test, tag and deploy

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-test-tag-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          pip install wheel pytest bump2version==1.0.0
          pip install .
      - name: Test with pytest
        run: |
          pytest --junitxml test-results.xml test/
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always() # Guarantees that this step always runs, even if the preceding test step fails
        with:
          files: test-results.xml
      - name: Increment version number and tag
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          bump2version patch
          git push --follow-tags
      - name: Deploy to PyPi
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          pip install setuptools
          pip install twine
          python setup.py sdist bdist_wheel
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
